# Generated by Django 3.1.5 on 2021-03-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('raza', models.CharField(max_length=64)),
                ('fh_nacimiento', models.DateTimeField()),
                ('valor_venta', models.IntegerField(null=True)),
            ],
        ),
    ]
