# Generated by Django 3.1.5 on 2021-03-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrega',
            name='decimales',
        ),
    ]
