# Generated by Django 3.1.5 on 2021-01-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='Media')),
                ('titulo', models.CharField(default='sin titulo', max_length=64)),
                ('texto', models.CharField(max_length=128, null=True)),
                ('pie_de_pagina', models.CharField(max_length=128, null=True)),
                ('habilitado', models.BooleanField()),
                ('fh_creacion', models.DateTimeField(auto_now_add=True)),
                ('fh_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
